"""
PDF Generator Service
ReportLab-based PDF building utilities with watermark and QR code support
"""

from io import BytesIO
from datetime import datetime
from typing import Optional, Dict, Any, List
import hashlib
import json

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, HRFlowable
)
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.barcharts import VerticalBarChart

import qrcode
from qrcode.image.pil import PilImage


class WatermarkCanvas(canvas.Canvas):
    """
    Custom canvas that adds watermark to every page.
    Watermark text is diagonal, semi-transparent.
    """

    def __init__(self, *args, watermark_text: str = "E-BARMM OFFICIAL DOCUMENT", **kwargs):
        super().__init__(*args, **kwargs)
        self.watermark_text = watermark_text
        self._saved_pages = []

    def showPage(self):
        """Override to add watermark before showing page."""
        self._draw_watermark()
        self._saved_pages.append(dict(self.__dict__))
        self._startPage()

    def _draw_watermark(self):
        """Draw diagonal watermark across the page."""
        self.saveState()

        # Set watermark properties
        self.setFont("Helvetica-Bold", 50)
        self.setFillColor(colors.Color(0.8, 0.8, 0.8, alpha=0.3))  # 30% opacity gray

        # Get page dimensions
        page_width, page_height = letter

        # Calculate center and draw rotated text
        self.translate(page_width / 2, page_height / 2)
        self.rotate(45)

        # Draw watermark text centered
        self.drawCentredString(0, 0, self.watermark_text)

        self.restoreState()

    def save(self):
        """Override save to add watermark to final page."""
        self._draw_watermark()
        super().save()


def generate_qr_code(data: str, size: int = 150) -> BytesIO:
    """
    Generate QR code image from data string.

    Args:
        data: The data to encode in the QR code
        size: Size of the QR code in pixels

    Returns:
        BytesIO containing PNG image data
    """
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=10,
        border=2,
    )
    qr.add_data(data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    # Convert to BytesIO
    buffer = BytesIO()
    img.save(buffer, format='PNG')
    buffer.seek(0)

    return buffer


def calculate_document_hash(
    report_type: str,
    project_id: Optional[str],
    data_snapshot: Dict[str, Any],
    generated_at: datetime
) -> str:
    """
    Calculate SHA-256 hash of report metadata and data snapshot.
    This enables verification that the report was generated by the official system.

    Args:
        report_type: Type of report (project_summary, progress_history, project_list)
        project_id: UUID of project (None for list reports)
        data_snapshot: Key data included in the report
        generated_at: Generation timestamp

    Returns:
        Hex-encoded SHA-256 hash
    """
    payload = {
        "report_type": report_type,
        "project_id": str(project_id) if project_id else None,
        "data_snapshot": data_snapshot,
        "generated_at": generated_at.isoformat()
    }

    # Canonical JSON (sorted keys, no whitespace)
    canonical_json = json.dumps(payload, sort_keys=True, separators=(',', ':'), default=str)

    # SHA-256 hash
    hash_bytes = hashlib.sha256(canonical_json.encode('utf-8')).digest()

    return hash_bytes.hex()


def get_verification_url(document_hash: str, report_type: str, project_id: Optional[str] = None) -> str:
    """
    Generate verification URL for the document.

    Args:
        document_hash: SHA-256 hash of the document
        report_type: Type of report
        project_id: Project ID if applicable

    Returns:
        Verification URL string
    """
    base_url = "https://ebarmm.gov.ph/verify"
    url = f"{base_url}/{document_hash}?type={report_type}"
    if project_id:
        url += f"&project={project_id}"
    return url


def get_styles() -> Dict[str, ParagraphStyle]:
    """
    Get custom paragraph styles for reports.

    Returns:
        Dictionary of named ParagraphStyle objects
    """
    styles = getSampleStyleSheet()

    custom_styles = {
        "Title": ParagraphStyle(
            "Title",
            parent=styles["Heading1"],
            fontSize=18,
            spaceAfter=20,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#1a365d")
        ),
        "Subtitle": ParagraphStyle(
            "Subtitle",
            parent=styles["Heading2"],
            fontSize=14,
            spaceAfter=10,
            textColor=colors.HexColor("#2d3748")
        ),
        "SectionHeader": ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading3"],
            fontSize=12,
            spaceBefore=15,
            spaceAfter=8,
            textColor=colors.HexColor("#2b6cb0"),
            borderWidth=1,
            borderColor=colors.HexColor("#e2e8f0"),
            borderPadding=5
        ),
        "Normal": ParagraphStyle(
            "Normal",
            parent=styles["Normal"],
            fontSize=10,
            spaceAfter=6
        ),
        "Small": ParagraphStyle(
            "Small",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#718096")
        ),
        "Footer": ParagraphStyle(
            "Footer",
            parent=styles["Normal"],
            fontSize=8,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#a0aec0")
        ),
        "TableHeader": ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.white,
            alignment=TA_CENTER
        ),
        "TableCell": ParagraphStyle(
            "TableCell",
            parent=styles["Normal"],
            fontSize=9,
            alignment=TA_LEFT
        ),
        "VerificationText": ParagraphStyle(
            "VerificationText",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#4a5568"),
            alignment=TA_CENTER
        )
    }

    return custom_styles


def build_header(
    report_title: str,
    report_subtitle: Optional[str] = None,
    generated_at: Optional[datetime] = None
) -> List:
    """
    Build standard report header elements.

    Args:
        report_title: Main title of the report
        report_subtitle: Optional subtitle
        generated_at: Generation timestamp

    Returns:
        List of flowable elements for the header
    """
    styles = get_styles()
    elements = []

    # System name and title
    elements.append(Paragraph("E-BARMM Infrastructure Transparency System", styles["Small"]))
    elements.append(Spacer(1, 5))
    elements.append(Paragraph(report_title, styles["Title"]))

    if report_subtitle:
        elements.append(Paragraph(report_subtitle, styles["Subtitle"]))

    # Generation timestamp
    if generated_at:
        timestamp_str = generated_at.strftime("%B %d, %Y at %I:%M %p")
        elements.append(Paragraph(f"Generated: {timestamp_str}", styles["Small"]))

    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    elements.append(Spacer(1, 15))

    return elements


def build_footer_content(
    document_id: str,
    verification_url: str,
    page_num: int,
    total_pages: int
) -> str:
    """
    Build footer text content.

    Args:
        document_id: Unique document identifier (hash prefix)
        verification_url: URL for verification
        page_num: Current page number
        total_pages: Total number of pages

    Returns:
        Formatted footer string
    """
    return f"Document ID: {document_id[:16]}... | Page {page_num} of {total_pages} | Verify at: {verification_url}"


def build_qr_section(
    document_hash: str,
    verification_url: str
) -> List:
    """
    Build QR code verification section for the report.

    Args:
        document_hash: SHA-256 hash of the document
        verification_url: URL for verification

    Returns:
        List of flowable elements for QR section
    """
    styles = get_styles()
    elements = []

    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    elements.append(Spacer(1, 15))
    elements.append(Paragraph("Document Verification", styles["SectionHeader"]))

    # Generate QR code
    qr_buffer = generate_qr_code(verification_url, size=100)
    qr_image = Image(qr_buffer, width=1.2*inch, height=1.2*inch)

    # Create verification info table
    verification_data = [
        [qr_image, [
            Paragraph(f"<b>Document Hash:</b>", styles["Small"]),
            Paragraph(f"<font size='7'>{document_hash}</font>", styles["Small"]),
            Spacer(1, 5),
            Paragraph(f"<b>Verification URL:</b>", styles["Small"]),
            Paragraph(f"<font size='7'>{verification_url}</font>", styles["Small"]),
            Spacer(1, 5),
            Paragraph("Scan QR code or visit URL to verify this document", styles["VerificationText"])
        ]]
    ]

    verification_table = Table(verification_data, colWidths=[1.5*inch, 4.5*inch])
    verification_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (0, 0), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))

    elements.append(verification_table)

    return elements


def build_data_table(
    headers: List[str],
    data: List[List[Any]],
    col_widths: Optional[List[float]] = None
) -> Table:
    """
    Build a styled data table.

    Args:
        headers: List of column header strings
        data: List of rows, each row is a list of cell values
        col_widths: Optional list of column widths

    Returns:
        Styled Table object
    """
    styles = get_styles()

    # Prepare header row with styled paragraphs
    header_row = [Paragraph(h, styles["TableHeader"]) for h in headers]

    # Prepare data rows
    data_rows = []
    for row in data:
        styled_row = []
        for cell in row:
            if isinstance(cell, str):
                styled_row.append(Paragraph(cell, styles["TableCell"]))
            else:
                styled_row.append(cell)
        data_rows.append(styled_row)

    # Combine header and data
    table_data = [header_row] + data_rows

    # Create table
    table = Table(table_data, colWidths=col_widths)

    # Apply table style
    table.setStyle(TableStyle([
        # Header styling
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2b6cb0")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),

        # Data styling
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('ALIGN', (0, 1), (-1, -1), 'LEFT'),

        # Grid
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),

        # Alternating row colors
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),

        # Padding
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))

    return table


def build_progress_bar(percentage: float, width: float = 4*inch, height: float = 0.3*inch) -> Drawing:
    """
    Build a visual progress bar.

    Args:
        percentage: Progress percentage (0-100)
        width: Width of the progress bar
        height: Height of the progress bar

    Returns:
        Drawing object containing the progress bar
    """
    drawing = Drawing(width, height)

    # Background (gray)
    bg = Rect(0, 0, width, height)
    bg.fillColor = colors.HexColor("#e2e8f0")
    bg.strokeColor = colors.HexColor("#cbd5e0")
    bg.strokeWidth = 1
    drawing.add(bg)

    # Progress fill (colored based on percentage)
    if percentage > 0:
        fill_width = (percentage / 100) * width

        # Color based on progress
        if percentage >= 80:
            fill_color = colors.HexColor("#48bb78")  # Green
        elif percentage >= 50:
            fill_color = colors.HexColor("#ecc94b")  # Yellow
        else:
            fill_color = colors.HexColor("#ed8936")  # Orange

        fill = Rect(0, 0, fill_width, height)
        fill.fillColor = fill_color
        fill.strokeColor = None
        drawing.add(fill)

    # Percentage text
    text = String(width / 2, height / 3, f"{percentage:.1f}%")
    text.fontName = "Helvetica-Bold"
    text.fontSize = 10
    text.fillColor = colors.HexColor("#1a202c")
    text.textAnchor = "middle"
    drawing.add(text)

    return drawing


def build_key_value_table(data: Dict[str, str], col_widths: Optional[List[float]] = None) -> Table:
    """
    Build a two-column key-value table.

    Args:
        data: Dictionary of key-value pairs
        col_widths: Optional column widths [key_width, value_width]

    Returns:
        Styled Table object
    """
    styles = get_styles()

    if col_widths is None:
        col_widths = [2*inch, 4*inch]

    table_data = []
    for key, value in data.items():
        table_data.append([
            Paragraph(f"<b>{key}</b>", styles["TableCell"]),
            Paragraph(str(value) if value else "-", styles["TableCell"])
        ])

    table = Table(table_data, colWidths=col_widths)
    table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#f7fafc")),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))

    return table


class PDFReportBuilder:
    """
    Builder class for creating PDF reports with watermark.
    """

    def __init__(
        self,
        buffer: BytesIO,
        pagesize=letter,
        watermark_text: str = "E-BARMM OFFICIAL DOCUMENT"
    ):
        """
        Initialize the PDF builder.

        Args:
            buffer: BytesIO buffer to write PDF to
            pagesize: Page size (letter or A4)
            watermark_text: Text for watermark
        """
        self.buffer = buffer
        self.pagesize = pagesize
        self.watermark_text = watermark_text
        self.elements = []
        self.styles = get_styles()

    def add_header(
        self,
        title: str,
        subtitle: Optional[str] = None,
        generated_at: Optional[datetime] = None
    ):
        """Add standard header to the report."""
        self.elements.extend(build_header(title, subtitle, generated_at))

    def add_section(self, title: str):
        """Add a section header."""
        self.elements.append(Paragraph(title, self.styles["SectionHeader"]))
        self.elements.append(Spacer(1, 10))

    def add_paragraph(self, text: str, style_name: str = "Normal"):
        """Add a paragraph of text."""
        self.elements.append(Paragraph(text, self.styles[style_name]))

    def add_spacer(self, height: float = 10):
        """Add vertical space."""
        self.elements.append(Spacer(1, height))

    def add_table(
        self,
        headers: List[str],
        data: List[List[Any]],
        col_widths: Optional[List[float]] = None
    ):
        """Add a data table."""
        table = build_data_table(headers, data, col_widths)
        self.elements.append(table)
        self.elements.append(Spacer(1, 10))

    def add_key_value_table(self, data: Dict[str, str], col_widths: Optional[List[float]] = None):
        """Add a key-value table."""
        table = build_key_value_table(data, col_widths)
        self.elements.append(table)
        self.elements.append(Spacer(1, 10))

    def add_progress_bar(self, percentage: float, label: Optional[str] = None):
        """Add a visual progress bar."""
        if label:
            self.elements.append(Paragraph(label, self.styles["Small"]))
        self.elements.append(build_progress_bar(percentage))
        self.elements.append(Spacer(1, 10))

    def add_qr_section(self, document_hash: str, verification_url: str):
        """Add QR code verification section."""
        self.elements.extend(build_qr_section(document_hash, verification_url))

    def add_page_break(self):
        """Add a page break."""
        self.elements.append(PageBreak())

    def add_horizontal_line(self):
        """Add a horizontal line."""
        self.elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))

    def build(self, document_hash: str) -> BytesIO:
        """
        Build the PDF document.

        Args:
            document_hash: Hash for footer display

        Returns:
            BytesIO containing the PDF
        """
        # Create document with custom canvas for watermark
        doc = SimpleDocTemplate(
            self.buffer,
            pagesize=self.pagesize,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )

        # Add page number callback
        def add_page_number(canvas, doc):
            canvas.saveState()
            canvas.setFont('Helvetica', 8)
            canvas.setFillColor(colors.HexColor("#a0aec0"))

            page_text = f"Page {doc.page}"
            canvas.drawRightString(
                self.pagesize[0] - 0.75*inch,
                0.5*inch,
                page_text
            )

            doc_text = f"Document ID: {document_hash[:16]}..."
            canvas.drawString(0.75*inch, 0.5*inch, doc_text)

            # Draw watermark
            canvas.setFont("Helvetica-Bold", 50)
            canvas.setFillColor(colors.Color(0.8, 0.8, 0.8, alpha=0.3))
            canvas.translate(self.pagesize[0] / 2, self.pagesize[1] / 2)
            canvas.rotate(45)
            canvas.drawCentredString(0, 0, self.watermark_text)

            canvas.restoreState()

        # Build PDF
        doc.build(self.elements, onFirstPage=add_page_number, onLaterPages=add_page_number)

        self.buffer.seek(0)
        return self.buffer
